name: Dawn Marie
favicon: null
layout_spectrum: 0.5161838375497609
typography_spectrum: 0.8093774060253054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f37988'
    - '#797a7d'
    - '#a0a1a4'
    - '#cdcdcf'
  brandStrength: 0.1875
  lightness: 0.8211894491687417
  saturation: 0.875
  rhythmicContrast: 0.70952482172288
purpose: []
